### ISSUE TITLE
[post] How to create GitHub Action that Gitlab CI understands - part #2

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/tomasvotruba.com#1192]
IMPORTANT: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#about-yaml-syntax-for-github-actions

This removes the annoying argument order issue

![image](https://user-images.githubusercontent.com/924196/116610256-a023e580-a935-11eb-9468-dd977b8b0bee.png)

**Comment by TomasVotruba** [comment]
## Github Actoin syntax

```yaml
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.some_parameter }}


↓

## Compatible Bash

```bash
script:
    - docker run . $VALUE
```
